Repository mamba-org/quetz-frontend, pull requests merged in 2022-08, with the labels that each got.

#128 Tos
  README.md
  environment.yml
  packages/_metapackage/package.json
  packages/_metapackage/src/index.ts
  packages/about-extension/package.json
  packages/about-extension/src/about.tsx
  packages/about-extension/src/index.ts
  packages/about-extension/style/base.css
  packages/about-extension/style/index.css
  packages/about-extension/style/index.js
  packages/about-extension/tsconfig.json
  packages/application/style/base.css
  quetz_frontend/app/index.js
  quetz_frontend/app/package.json
  quetz_frontend/backend.py
  yarn.lock
Labels: enhancement

#108 Add jupyter releaser
  .github/workflows/check-release.yml
  .github/workflows/enforce-label.yml
  CHANGELOG.md
  LICENSE
  MANIFEST.in
  RELEASE.md
  examples/light_theme/README.md
  lerna.json
  package.json
  pyproject.toml
  quetz_frontend/_version.py
  quetz_frontend/app/package.json
  scripts/bump-version.py
  setup.cfg
  yarn.lock
Labels: maintenance

#131 Automated Changelog Entry for 0.4.0a0 on main
  CHANGELOG.md
Labels: documentation

#132 Fix build
  quetz_frontend/app/package.json
  scripts/bump-version.py
  setup.cfg
Labels: bug, maintenance

#133 Automated Changelog Entry for 0.4.0a1 on main
  CHANGELOG.md
Labels: documentation
